var express = require('express');
var path = require('path');

var app = express();
var port = 8000;

app.listen(port);
console.log(`Server started at http://localhost:${port}`);

// =================================================
// Static Assets
// =================================================
app.use('/public/css', express.static(path.resolve(__dirname, 'public', 'css')));
app.use('/public/img', express.static(path.resolve(__dirname, 'public', 'img')));
app.use('/public/html', express.static(path.resolve(__dirname, 'public', 'html')));
app.use('/public', express.static(path.resolve(__dirname, 'public')));

// =================================================
// Dynamic (Compiled) Assets
// =================================================
// project-level `/dist` folder (generated by build)
app.use(express.static(path.resolve(__dirname, 'dist'), {
  etag: false
}));

// =================================================
// Routes
// =================================================
// This is the original page we worked on
app.get('/public/html', function(req,res) {
  res.sendFile(path.resolve(__dirname, 'public', 'html', 'customer-list.html'));
});

// This is the new base route that links to our generated assets
app.get('/', function(req,res) {
  res.sendFile(path.resolve(__dirname, 'app', 'views', 'index.html'));
});
